# Generated by Django 6.0 on 2025-12-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
