# Generated by Django 5.2.4 on 2025-12-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE_NUMBER', models.CharField(max_length=10)),
                ('AGE', models.IntegerField()),
                ('EMP_PHOTO', models.ImageField(upload_to='EmpProfile')),
            ],
        ),
    ]
