# Generated by Django 5.2.4 on 2025-12-11 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STU_NAME', models.CharField(max_length=50)),
                ('STU_SURENAME', models.CharField(max_length=50)),
                ('STU_BIRTHDATE', models.DateField()),
                ('EMAIL', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email not valid. Write like this: guess1@gmail.com', regex='^[A-Za-z0-9._]+@[A-Za-z]+\\.[A-Za-z]{2,}$')])),
                ('CONTACT_NUMBER', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('STU_PHOTO', models.ImageField(upload_to='STUDENT_PROFILE')),
            ],
        ),
    ]
