# Generated by Django 5.2.4 on 2025-12-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departmetn',
            new_name='department',
        ),
    ]
