# Generated by Django 5.2.4 on 2025-12-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_CRUD', '0002_rename_departmetn_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='EmployeeProfile'),
        ),
    ]
