# Generated by Django 5.2.4 on 2025-12-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_CRUD', '0003_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='EmployeeProfile/Defailt.jpg', upload_to='EmployeeProfile'),
        ),
    ]
