# Generated by Django 5.2.4 on 2025-12-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_CRUD', '0005_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='EmployeeProfile/Default.jpg', null=True, upload_to='EmployeeProfile'),
        ),
    ]
