# Generated by Django 5.2.4 on 2025-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='IT', max_length=30),
            preserve_default=False,
        ),
    ]
