# Generated by Django 5.2.4 on 2025-12-11 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='PHONE_NUMBER',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits.')]),
        ),
    ]
