# Generated by Django 5.2.4 on 2025-12-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
